import dotenv from "dotenv";
import mongoose, { Types } from "mongoose";
import Product from "../src/models/product.model";
import { ProductStatus, StockStatus } from "../src/interfaces/product.interface";

dotenv.config();

const seedUserId = new Types.ObjectId("64f000000000000000000001");
const categoryIds = {
    electronics: new Types.ObjectId("64f000000000000000000101"),
    computers: new Types.ObjectId("64f000000000000000000102"),
    home: new Types.ObjectId("64f000000000000000000103"),
    fitness: new Types.ObjectId("64f000000000000000000104"),
    lifestyle: new Types.ObjectId("64f000000000000000000105"),
};
const brandIds = {
    aurora: new Types.ObjectId("64f000000000000000000201"),
    nova: new Types.ObjectId("64f000000000000000000202"),
    summit: new Types.ObjectId("64f000000000000000000203"),
    homestead: new Types.ObjectId("64f000000000000000000204"),
    pulse: new Types.ObjectId("64f000000000000000000205"),
};

const sampleProducts = [
    {
        name: "Aurora Noise-Cancelling Headphones",
        slug: "aurora-noise-cancelling-headphones",
        sku: "DEV-AUR-HEADPHONES-001",
        shortDescription: "Wireless over-ear headphones with adaptive noise cancellation.",
        description: "Comfortable Bluetooth headphones built for focused work, travel, and daily listening.",
        price: 149.99,
        comparePrice: 199.99,
        costPrice: 82,
        currency: "USD",
        quantity: 35,
        lowStockThreshold: 8,
        category: categoryIds.electronics,
        brand: brandIds.aurora,
        images: ["https://placehold.co/800x800?text=Aurora+Headphones"],
        thumbnail: "https://placehold.co/400x400?text=Aurora+Headphones",
        tags: ["audio", "wireless", "travel"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 0.32,
        seoTitle: "Aurora Noise-Cancelling Headphones",
        seoDescription: "Premium wireless headphones with adaptive noise cancellation.",
        seoKeywords: ["headphones", "audio", "wireless"],
        createdBy: seedUserId,
    },
    {
        name: "Nova 14-Inch Ultrabook",
        slug: "nova-14-inch-ultrabook",
        sku: "DEV-NOVA-ULTRABOOK-002",
        shortDescription: "Lightweight laptop with all-day battery life and a vivid display.",
        description: "A portable productivity laptop for business users, students, and creators.",
        price: 1099,
        comparePrice: 1299,
        costPrice: 760,
        currency: "USD",
        quantity: 18,
        lowStockThreshold: 5,
        category: categoryIds.computers,
        brand: brandIds.nova,
        images: ["https://placehold.co/800x800?text=Nova+Ultrabook"],
        thumbnail: "https://placehold.co/400x400?text=Nova+Ultrabook",
        tags: ["laptop", "productivity", "portable"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 1.18,
        seoTitle: "Nova 14-Inch Ultrabook",
        seoDescription: "Thin and light laptop with all-day performance.",
        seoKeywords: ["laptop", "ultrabook", "computer"],
        createdBy: seedUserId,
    },
    {
        name: "Summit Trail Running Shoes",
        slug: "summit-trail-running-shoes",
        sku: "DEV-SUM-TRAILSHOE-003",
        shortDescription: "Durable trail shoes with grippy outsole and cushioned support.",
        description: "Built for mixed terrain, weekend hikes, and daily outdoor training.",
        price: 124.5,
        comparePrice: 149.99,
        costPrice: 58,
        currency: "USD",
        quantity: 42,
        lowStockThreshold: 10,
        category: categoryIds.fitness,
        brand: brandIds.summit,
        images: ["https://placehold.co/800x800?text=Trail+Shoes"],
        thumbnail: "https://placehold.co/400x400?text=Trail+Shoes",
        tags: ["running", "outdoor", "fitness"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.74,
        seoTitle: "Summit Trail Running Shoes",
        seoDescription: "Trail-ready running shoes with durable grip and cushion.",
        seoKeywords: ["running shoes", "trail", "fitness"],
        createdBy: seedUserId,
    },
    {
        name: "Homestead Ceramic Dinnerware Set",
        slug: "homestead-ceramic-dinnerware-set",
        sku: "DEV-HOME-DINNERWARE-004",
        shortDescription: "Sixteen-piece ceramic dinnerware set with a matte glaze finish.",
        description: "Dishwasher-safe plates and bowls for everyday dining and entertaining.",
        price: 89.99,
        comparePrice: 119.99,
        costPrice: 39,
        currency: "USD",
        quantity: 27,
        lowStockThreshold: 6,
        category: categoryIds.home,
        brand: brandIds.homestead,
        images: ["https://placehold.co/800x800?text=Dinnerware+Set"],
        thumbnail: "https://placehold.co/400x400?text=Dinnerware+Set",
        tags: ["kitchen", "dining", "home"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 7.4,
        seoTitle: "Homestead Ceramic Dinnerware Set",
        seoDescription: "Modern sixteen-piece ceramic dinnerware set.",
        seoKeywords: ["dinnerware", "ceramic", "home"],
        createdBy: seedUserId,
    },
    {
        name: "Pulse Smart Fitness Watch",
        slug: "pulse-smart-fitness-watch",
        sku: "DEV-PULSE-WATCH-005",
        shortDescription: "GPS fitness watch with heart-rate tracking and sleep insights.",
        description: "Track workouts, recovery, notifications, and health metrics from your wrist.",
        price: 229,
        comparePrice: 279,
        costPrice: 118,
        currency: "USD",
        quantity: 22,
        lowStockThreshold: 5,
        category: categoryIds.fitness,
        brand: brandIds.pulse,
        images: ["https://placehold.co/800x800?text=Fitness+Watch"],
        thumbnail: "https://placehold.co/400x400?text=Fitness+Watch",
        tags: ["wearable", "fitness", "gps"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 0.06,
        seoTitle: "Pulse Smart Fitness Watch",
        seoDescription: "GPS smartwatch for workouts and health tracking.",
        seoKeywords: ["fitness watch", "smartwatch", "wearable"],
        createdBy: seedUserId,
    },
    {
        name: "Aurora Bluetooth Bookshelf Speakers",
        slug: "aurora-bluetooth-bookshelf-speakers",
        sku: "DEV-AUR-SPEAKERS-006",
        shortDescription: "Compact powered speakers with rich stereo sound and Bluetooth input.",
        description: "A stylish speaker pair for desks, shelves, apartments, and home offices.",
        price: 179.99,
        comparePrice: 229.99,
        costPrice: 94,
        currency: "USD",
        quantity: 16,
        lowStockThreshold: 4,
        category: categoryIds.electronics,
        brand: brandIds.aurora,
        images: ["https://placehold.co/800x800?text=Bookshelf+Speakers"],
        thumbnail: "https://placehold.co/400x400?text=Bookshelf+Speakers",
        tags: ["audio", "speakers", "bluetooth"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 5.1,
        seoTitle: "Aurora Bluetooth Bookshelf Speakers",
        seoDescription: "Powered Bluetooth bookshelf speakers for room-filling sound.",
        seoKeywords: ["speakers", "bluetooth", "audio"],
        createdBy: seedUserId,
    },
    {
        name: "Nova Mechanical Keyboard Pro",
        slug: "nova-mechanical-keyboard-pro",
        sku: "DEV-NOVA-KEYBOARD-007",
        shortDescription: "Hot-swappable mechanical keyboard with quiet tactile switches.",
        description: "A premium keyboard for developers, writers, gamers, and office setups.",
        price: 139,
        comparePrice: 169,
        costPrice: 65,
        currency: "USD",
        quantity: 30,
        lowStockThreshold: 8,
        category: categoryIds.computers,
        brand: brandIds.nova,
        images: ["https://placehold.co/800x800?text=Keyboard+Pro"],
        thumbnail: "https://placehold.co/400x400?text=Keyboard+Pro",
        tags: ["keyboard", "mechanical", "workspace"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.95,
        seoTitle: "Nova Mechanical Keyboard Pro",
        seoDescription: "Hot-swappable tactile mechanical keyboard.",
        seoKeywords: ["keyboard", "mechanical", "computer"],
        createdBy: seedUserId,
    },
    {
        name: "Homestead Organic Cotton Sheet Set",
        slug: "homestead-organic-cotton-sheet-set",
        sku: "DEV-HOME-SHEETS-008",
        shortDescription: "Breathable organic cotton sheets with a soft percale weave.",
        description: "Hotel-inspired bedding designed for cool comfort and everyday durability.",
        price: 74.99,
        comparePrice: 99.99,
        costPrice: 31,
        currency: "USD",
        quantity: 40,
        lowStockThreshold: 10,
        category: categoryIds.home,
        brand: brandIds.homestead,
        images: ["https://placehold.co/800x800?text=Cotton+Sheets"],
        thumbnail: "https://placehold.co/400x400?text=Cotton+Sheets",
        tags: ["bedding", "cotton", "home"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 1.8,
        seoTitle: "Homestead Organic Cotton Sheet Set",
        seoDescription: "Soft organic cotton sheets for breathable comfort.",
        seoKeywords: ["sheets", "bedding", "organic cotton"],
        createdBy: seedUserId,
    },
    {
        name: "Summit Insulated Water Bottle",
        slug: "summit-insulated-water-bottle",
        sku: "DEV-SUM-BOTTLE-009",
        shortDescription: "Stainless steel bottle that keeps drinks cold for up to 24 hours.",
        description: "Leak-resistant insulated bottle for commuting, hiking, and gym sessions.",
        price: 32.5,
        comparePrice: 44,
        costPrice: 12,
        currency: "USD",
        quantity: 75,
        lowStockThreshold: 15,
        category: categoryIds.lifestyle,
        brand: brandIds.summit,
        images: ["https://placehold.co/800x800?text=Water+Bottle"],
        thumbnail: "https://placehold.co/400x400?text=Water+Bottle",
        tags: ["hydration", "outdoor", "fitness"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.41,
        seoTitle: "Summit Insulated Water Bottle",
        seoDescription: "Leak-resistant stainless steel insulated water bottle.",
        seoKeywords: ["water bottle", "insulated", "outdoor"],
        createdBy: seedUserId,
    },
    {
        name: "Pulse Resistance Band Kit",
        slug: "pulse-resistance-band-kit",
        sku: "DEV-PULSE-BANDS-010",
        shortDescription: "Five-band training kit for strength, rehab, and mobility workouts.",
        description: "Portable resistance bands with handles, door anchor, and carrying pouch.",
        price: 28.99,
        comparePrice: 39.99,
        costPrice: 10,
        currency: "USD",
        quantity: 64,
        lowStockThreshold: 12,
        category: categoryIds.fitness,
        brand: brandIds.pulse,
        images: ["https://placehold.co/800x800?text=Resistance+Bands"],
        thumbnail: "https://placehold.co/400x400?text=Resistance+Bands",
        tags: ["fitness", "strength", "portable"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.58,
        seoTitle: "Pulse Resistance Band Kit",
        seoDescription: "Portable resistance band set for full-body training.",
        seoKeywords: ["resistance bands", "fitness", "strength"],
        createdBy: seedUserId,
    },
    {
        name: "Aurora 4K Streaming Stick",
        slug: "aurora-4k-streaming-stick",
        sku: "DEV-AUR-STREAMING-011",
        shortDescription: "Compact 4K streaming device with voice remote and fast app launch.",
        description: "Upgrade any compatible TV with crisp streaming, quick search, and simple setup.",
        price: 49.99,
        comparePrice: 59.99,
        costPrice: 21,
        currency: "USD",
        quantity: 55,
        lowStockThreshold: 10,
        category: categoryIds.electronics,
        brand: brandIds.aurora,
        images: ["https://placehold.co/800x800?text=Streaming+Stick"],
        thumbnail: "https://placehold.co/400x400?text=Streaming+Stick",
        tags: ["streaming", "tv", "4k"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.09,
        seoTitle: "Aurora 4K Streaming Stick",
        seoDescription: "4K streaming stick with voice remote and fast setup.",
        seoKeywords: ["streaming", "4k", "tv"],
        createdBy: seedUserId,
    },
    {
        name: "Nova USB-C Docking Station",
        slug: "nova-usb-c-docking-station",
        sku: "DEV-NOVA-DOCK-012",
        shortDescription: "Multi-port USB-C dock with HDMI, Ethernet, USB, and power delivery.",
        description: "Connect monitors, peripherals, and wired networking with one cable.",
        price: 119,
        comparePrice: 149,
        costPrice: 54,
        currency: "USD",
        quantity: 25,
        lowStockThreshold: 6,
        category: categoryIds.computers,
        brand: brandIds.nova,
        images: ["https://placehold.co/800x800?text=USB-C+Dock"],
        thumbnail: "https://placehold.co/400x400?text=USB-C+Dock",
        tags: ["usb-c", "dock", "workspace"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 0.44,
        seoTitle: "Nova USB-C Docking Station",
        seoDescription: "Multi-port USB-C dock for productive desk setups.",
        seoKeywords: ["usb-c", "dock", "laptop"],
        createdBy: seedUserId,
    },
    {
        name: "Homestead Cast Iron Skillet",
        slug: "homestead-cast-iron-skillet",
        sku: "DEV-HOME-SKILLET-013",
        shortDescription: "Pre-seasoned cast iron skillet for stovetop, oven, and campfire cooking.",
        description: "A durable kitchen essential with excellent heat retention and versatility.",
        price: 38,
        comparePrice: 52,
        costPrice: 14,
        currency: "USD",
        quantity: 47,
        lowStockThreshold: 10,
        category: categoryIds.home,
        brand: brandIds.homestead,
        images: ["https://placehold.co/800x800?text=Cast+Iron+Skillet"],
        thumbnail: "https://placehold.co/400x400?text=Cast+Iron+Skillet",
        tags: ["kitchen", "cookware", "home"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 2.9,
        seoTitle: "Homestead Cast Iron Skillet",
        seoDescription: "Pre-seasoned cast iron skillet for versatile cooking.",
        seoKeywords: ["skillet", "cast iron", "cookware"],
        createdBy: seedUserId,
    },
    {
        name: "Summit Daypack 24L",
        slug: "summit-daypack-24l",
        sku: "DEV-SUM-DAYPACK-014",
        shortDescription: "Lightweight daypack with hydration sleeve and laptop compartment.",
        description: "A versatile backpack for trails, commuting, travel, and everyday carry.",
        price: 68.5,
        comparePrice: 89.5,
        costPrice: 29,
        currency: "USD",
        quantity: 33,
        lowStockThreshold: 7,
        category: categoryIds.lifestyle,
        brand: brandIds.summit,
        images: ["https://placehold.co/800x800?text=Daypack+24L"],
        thumbnail: "https://placehold.co/400x400?text=Daypack+24L",
        tags: ["backpack", "travel", "outdoor"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 0.82,
        seoTitle: "Summit Daypack 24L",
        seoDescription: "Lightweight 24L daypack for trail and commute.",
        seoKeywords: ["daypack", "backpack", "outdoor"],
        createdBy: seedUserId,
    },
    {
        name: "Pulse Yoga Mat Pro",
        slug: "pulse-yoga-mat-pro",
        sku: "DEV-PULSE-YOGAMAT-015",
        shortDescription: "Non-slip yoga mat with dense cushioning and alignment markers.",
        description: "Stable, supportive mat for yoga, pilates, stretching, and floor workouts.",
        price: 46,
        comparePrice: 64,
        costPrice: 18,
        currency: "USD",
        quantity: 58,
        lowStockThreshold: 12,
        category: categoryIds.fitness,
        brand: brandIds.pulse,
        images: ["https://placehold.co/800x800?text=Yoga+Mat+Pro"],
        thumbnail: "https://placehold.co/400x400?text=Yoga+Mat+Pro",
        tags: ["yoga", "fitness", "mat"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 1.2,
        seoTitle: "Pulse Yoga Mat Pro",
        seoDescription: "Non-slip cushioned yoga mat for studio and home workouts.",
        seoKeywords: ["yoga mat", "fitness", "pilates"],
        createdBy: seedUserId,
    },
    {
        name: "Aurora Portable Bluetooth Speaker",
        slug: "aurora-portable-bluetooth-speaker",
        sku: "DEV-AUR-PORTSPEAKER-016",
        shortDescription: "Water-resistant portable speaker with punchy bass and 12-hour battery.",
        description: "Take music to the patio, park, beach, or workspace with simple Bluetooth pairing.",
        price: 69.99,
        comparePrice: 89.99,
        costPrice: 30,
        currency: "USD",
        quantity: 49,
        lowStockThreshold: 9,
        category: categoryIds.electronics,
        brand: brandIds.aurora,
        images: ["https://placehold.co/800x800?text=Portable+Speaker"],
        thumbnail: "https://placehold.co/400x400?text=Portable+Speaker",
        tags: ["audio", "bluetooth", "portable"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.62,
        seoTitle: "Aurora Portable Bluetooth Speaker",
        seoDescription: "Portable water-resistant Bluetooth speaker with long battery life.",
        seoKeywords: ["speaker", "bluetooth", "portable audio"],
        createdBy: seedUserId,
    },
    {
        name: "Nova Ergonomic Wireless Mouse",
        slug: "nova-ergonomic-wireless-mouse",
        sku: "DEV-NOVA-MOUSE-017",
        shortDescription: "Rechargeable ergonomic mouse with silent clicks and precision tracking.",
        description: "Comfort-focused wireless mouse designed for long work sessions and travel.",
        price: 54.99,
        comparePrice: 69.99,
        costPrice: 22,
        currency: "USD",
        quantity: 52,
        lowStockThreshold: 10,
        category: categoryIds.computers,
        brand: brandIds.nova,
        images: ["https://placehold.co/800x800?text=Wireless+Mouse"],
        thumbnail: "https://placehold.co/400x400?text=Wireless+Mouse",
        tags: ["mouse", "wireless", "workspace"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.14,
        seoTitle: "Nova Ergonomic Wireless Mouse",
        seoDescription: "Rechargeable ergonomic wireless mouse with silent clicks.",
        seoKeywords: ["mouse", "wireless mouse", "computer"],
        createdBy: seedUserId,
    },
    {
        name: "Homestead Bamboo Storage Bins",
        slug: "homestead-bamboo-storage-bins",
        sku: "DEV-HOME-STORAGE-018",
        shortDescription: "Stackable bamboo storage bins for pantry, bath, and office organization.",
        description: "Durable storage bins that bring a clean, natural look to any room.",
        price: 42.99,
        comparePrice: 56.99,
        costPrice: 17,
        currency: "USD",
        quantity: 38,
        lowStockThreshold: 8,
        category: categoryIds.home,
        brand: brandIds.homestead,
        images: ["https://placehold.co/800x800?text=Bamboo+Storage"],
        thumbnail: "https://placehold.co/400x400?text=Bamboo+Storage",
        tags: ["storage", "organization", "home"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 1.6,
        seoTitle: "Homestead Bamboo Storage Bins",
        seoDescription: "Stackable bamboo bins for home organization.",
        seoKeywords: ["storage bins", "organization", "bamboo"],
        createdBy: seedUserId,
    },
    {
        name: "Summit Polarized Sunglasses",
        slug: "summit-polarized-sunglasses",
        sku: "DEV-SUM-SUNGLASSES-019",
        shortDescription: "Lightweight polarized sunglasses with UV400 protection.",
        description: "Everyday outdoor sunglasses for driving, hiking, travel, and beach days.",
        price: 59,
        comparePrice: 79,
        costPrice: 20,
        currency: "USD",
        quantity: 44,
        lowStockThreshold: 9,
        category: categoryIds.lifestyle,
        brand: brandIds.summit,
        images: ["https://placehold.co/800x800?text=Polarized+Sunglasses"],
        thumbnail: "https://placehold.co/400x400?text=Polarized+Sunglasses",
        tags: ["sunglasses", "outdoor", "travel"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.IN_STOCK,
        isFeatured: false,
        isDigital: false,
        weight: 0.05,
        seoTitle: "Summit Polarized Sunglasses",
        seoDescription: "Lightweight polarized sunglasses with UV400 protection.",
        seoKeywords: ["sunglasses", "polarized", "outdoor"],
        createdBy: seedUserId,
    },
    {
        name: "Pulse Adjustable Dumbbell Pair",
        slug: "pulse-adjustable-dumbbell-pair",
        sku: "DEV-PULSE-DUMBBELLS-020",
        shortDescription: "Space-saving adjustable dumbbells for strength training at home.",
        description: "Quick-select dumbbells that replace multiple weight pairs in a compact design.",
        price: 299,
        comparePrice: 359,
        costPrice: 168,
        currency: "USD",
        quantity: 9,
        lowStockThreshold: 10,
        category: categoryIds.fitness,
        brand: brandIds.pulse,
        images: ["https://placehold.co/800x800?text=Adjustable+Dumbbells"],
        thumbnail: "https://placehold.co/400x400?text=Adjustable+Dumbbells",
        tags: ["fitness", "strength", "home gym"],
        status: ProductStatus.ACTIVE,
        stockStatus: StockStatus.LOW_STOCK,
        isFeatured: true,
        isDigital: false,
        weight: 22.7,
        seoTitle: "Pulse Adjustable Dumbbell Pair",
        seoDescription: "Compact adjustable dumbbells for home strength training.",
        seoKeywords: ["dumbbells", "strength", "home gym"],
        createdBy: seedUserId,
    },
];

const run = async (): Promise<void> => {
    if (process.env.NODE_ENV === "production") {
        throw new Error("Refusing to seed products when NODE_ENV=production.");
    }

    if (!process.env.MONGODB_URI) {
        throw new Error("MONGODB_URI is required to seed development products.");
    }

    await mongoose.connect(process.env.MONGODB_URI);

    const seedSkus = sampleProducts.map((product) => product.sku);
    const existingProducts = await Product.find({ sku: { $in: seedSkus } })
        .select("sku")
        .lean<{ sku: string }[]>();
    const existingSkus = new Set(existingProducts.map((product) => product.sku));
    const productsToInsert = sampleProducts.filter((product) => !existingSkus.has(product.sku));

    if (productsToInsert.length === 0) {
        console.log("Development products already exist. No new products inserted.");
        return;
    }

    await Product.insertMany(productsToInsert, { ordered: false });
    console.log(`Inserted ${productsToInsert.length} development products into the products collection.`);
};

run()
    .catch((error) => {
        console.error("Failed to seed development products.");
        console.error(error);
        process.exitCode = 1;
    })
    .finally(async () => {
        await mongoose.disconnect();
    });
